# Generated by Django 5.1.7 on 2025-03-23 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelTable(
            name='book',
            table='books',
        ),
    ]
